deactivate term caching
necessary because of NoSuchMethodError

Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Objects.firstNonNull(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        at com.google.common.cache.CacheBuilder.getKeyStrength(CacheBuilder.java:472)
        at com.google.common.cache.LocalCache.<init>(LocalCache.java:236)
        at com.google.common.cache.LocalCache$LocalManualCache.<init>(LocalCache.java:4750)
        at com.google.common.cache.LocalCache$LocalLoadingCache.<init>(LocalCache.java:4858)
        at com.google.common.cache.CacheBuilder.build(CacheBuilder.java:739)
        at edu.umass.ciir.kbbridge.search.GalagoRetrieval.<init>(GalagoRetrieval.scala:28)